services:
  postgres:
    image: postgres:15-alpine
    container_name: medusa-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-my-medusa-store
    ports:
      - "5432:5432"
    volumes:
      - medusa_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  medusa:
    build: .
    container_name: medusa-backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "9000:9000"
    command: ["/bin/bash", "/usr/local/bin/docker-entrypoint.sh"]

volumes:
  medusa_pgdata:

